AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Role: arn:aws:iam::992382381506:role/LambdaExecutionRole
      CodeUri: s3://lr-bucket-s3/lambda_function.zip
      Runtime: python3.8
      Timeout: 15
      MemorySize: 128
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            Path: /hello
            Method: get
Outputs:
  HelloWorldApiUrl:
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello'
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
