AWSTemplateFormatVersion: '2010-09-09'
Resources:
  HelloWorldFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Role: arn:aws:iam::992382381506:role/LambdaExecutionRole
      Code:
        S3Bucket: nombre-de-tu-bucket-s3
        S3Key: lambda_function.zip
      Runtime: python3.8
      Timeout: 15
      MemorySize: 128

  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: HelloWorldApi

  Resource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt 'ApiGateway.RootResourceId'
      PathPart: 'hello'
      RestApiId: !Ref 'ApiGateway'

  Method:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: GET
      ResourceId: !Ref 'Resource'
      RestApiId: !Ref 'ApiGateway'
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HelloWorldFunction.Arn}/invocations'

  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !GetAtt 'HelloWorldFunction.Arn'
      Principal: 'apigateway.amazonaws.com'

Outputs:
  EndpointUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub 'https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod/hello'
