AWSTemplateFormatVersion: '2010-09-09'
Resources:
  HelloWorldFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Role: arn:aws:iam::YOUR_ACCOUNT_ID:role/YOUR_LAMBDA_EXEC_ROLE  # Asegúrate de reemplazar esto con el ARN correcto del rol IAM
      Code:
        ZipFile: |
          import json

          def lambda_handler(event, context):
              return {
                  'statusCode': 200,
                  'body': json.dumps('Hello World')
              }
      Runtime: python3.8
      Timeout: 15
      MemorySize: 128

  HelloWorldApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: HelloWorldApi

  HelloWorldApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - HelloWorldApi
          - RootResourceId
      PathPart: hello
      RestApiId:
        Ref: HelloWorldApi

  HelloWorldApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: GET
      ResourceId:
        Ref: HelloWorldApiResource
      RestApiId:
        Ref: HelloWorldApi
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HelloWorldFunction.Arn}/invocations

  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: HelloWorldFunction
      Principal: apigateway.amazonaws.com

Outputs:
  HelloWorldApiUrl:
    Value:
      Fn::Sub: https://${HelloWorldApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
